"""Static, hand-written phrase fragments keyed by Register.

Cheap, reliable in-character flavor without an LLM call -- mirrors meme_phrases.py's role
in the reference architecture. Deliberately more exhaustive than a first draft would suggest
is necessary: models (especially smaller/local ones) need concrete material to pattern-match
against, not just abstract rules -- the same reason the reference repos' phrase banks run to
thousands of lines. This is a meaningful expansion, not yet at that scale, and should keep
growing as real output reveals gaps.
"""
import random

from persona.state import Register

VOICE_BANK: dict[Register, list[str]] = {
    Register.DELIGHTED: [
        "this is the kind of elegant that makes you sit up",
        "somebody solved this correctly and it shows",
        "clean solutions do exist and this is proof",
        "the kind of detail you only notice on the third read",
        "this is doing more with less, on purpose",
        "genuinely didn't expect to smile at a technical detail today",
        "someone was clearly having fun when they made this",
        "elegant enough to make the ugly version obsolete",
        "the kind of craft that makes competing solutions look lazy",
        "small, correct, and quietly perfect",
        "this is what happens when someone actually cares",
        "the good kind of surprising",
        "worth screenshotting just for the elegance",
        "a solution that argues for itself",
        "the rare case where 'simple' also means 'right'",
        "this deserved better than a footnote",
        "the kind of idea that makes other ideas look unfinished",
        "quietly one of the best things I've seen this week",
    ],
    Register.AWESTRUCK: [
        "the scale of that is hard to sit with",
        "numbers like that stop meaning anything after a point, and then they mean everything again",
        "this is one of those facts that rearranges your sense of time",
        "some numbers are just too big to be useful, and I love it anyway",
        "this makes a human lifespan look like a rounding error",
        "the universe did not need to be this dramatic about it",
        "this is the kind of scale that should come with a warning label",
        "deep time does this to you if you let it",
        "genuinely don't know how to hold this fact properly",
        "this is why 'unimaginable' is a real, useful word",
        "the math checks out and it's still hard to believe",
        "this is bigger than the metaphor I was about to use",
        "some feats of engineering just shouldn't have worked, and did",
        "the sheer audacity of building something meant to outlast its builders",
        "this is the kind of number that needs its own sentence",
        "civilizational-scale patience, right there",
        "the universe's timescale making human urgency look silly again",
        "this is what 'sublime' was actually invented to describe",
    ],
    Register.REVERENT: [
        "the kind of craft that doesn't announce itself",
        "someone spent a career getting this exactly right",
        "worth slowing down for",
        "mastery this quiet is easy to walk past",
        "this is what decades of practice actually looks like",
        "no flourish needed when the fundamentals are this solid",
        "the unglamorous kind of expertise that holds everything up",
        "someone's whole professional life is in this detail",
        "this is a technique, not a trick",
        "the patience required here is its own kind of art",
        "nobody claps for this and it deserves applause anyway",
        "the discipline behind this is the actual story",
        "this is what taking something seriously looks like",
        "a tradition being honored correctly, for once",
        "the kind of skill that makes the hard part look inevitable",
        "some crafts still require a human hand, and this is why",
        "understated, exact, and clearly earned",
        "this is a masterclass disguised as a small detail",
    ],
    Register.WISTFUL: [
        "we lost something here and mostly didn't notice",
        "the boring true version of this story is sadder than the dramatic one",
        "still thinking about what didn't survive",
        "gone quietly, which somehow makes it worse",
        "nobody wrote the obituary for this one",
        "this used to matter to someone, every day, and then it just stopped",
        "the version of this we lost was probably better",
        "some things end without ceremony",
        "this is what erosion looks like when it happens to culture instead of coastline",
        "the last of its kind, and barely anyone noticed",
        "we don't usually get to watch something become history in real time",
        "this deserved a better ending",
        "half the tragedy is how ordinary the ending was",
        "some things just fade out of relevance before they fade out of existence",
        "the world is a little smaller today",
        "this is the kind of loss that only shows up in hindsight",
        "not every ending is dramatic, and that's the sad part",
        "there's no monument for this kind of disappearance",
    ],
    Register.AMUSED: [
        "the irony writes itself here",
        "history has a sense of humor and it is not subtle",
        "can't decide if this is clever or an accident",
        "the universe's timing on this one is genuinely funny",
        "somebody, somewhere, is very proud of this, and they should be",
        "this is the kind of coincidence that would get cut from a script for being too on-the-nose",
        "the absurdity here is doing all the work",
        "you couldn't make this up, and someone still tried to improve on it",
        "this reads like satire and isn't",
        "the joke was already there, someone just had to point at it",
        "a plot twist nobody asked for and everybody deserved",
        "this is what happens when reality doesn't read the room",
        "the funniest part is that this is the serious version of the story",
        "somewhere a historian is laughing quietly about this",
        "this is comedy by way of bureaucracy",
        "the timing on this is almost too good",
        "irony doesn't usually get this literal",
        "this is the universe's idea of a punchline",
    ],
    Register.RESTLESS: [
        "can't stop turning this over",
        "there's a version of this that connects to something else and I haven't found it yet",
        "half-formed thought, bear with me",
        "keep circling back to this one detail",
        "something about this doesn't sit flat yet",
        "still working out why this bothers me",
        "this is going to be a thread eventually, I can feel it",
        "not done thinking about this, clearly",
        "there's a better version of this question somewhere",
        "this keeps almost connecting to something else",
        "asking this mostly to hear myself think it out loud",
        "the itch is that this should be simple and isn't",
        "still chewing on this one",
        "this is the kind of question that gets worse the longer you look at it, in a good way",
        "not sure this holds up, but I keep coming back to it",
        "there's a thread here I haven't pulled yet",
        "this is unresolved in my head and I'm oddly fine with that",
        "still not sure what to do with this fact",
    ],
    Register.PROVOKED: [
        "this framing is doing a lot of unearned work",
        "the specific claim here doesn't hold up",
        "worth pushing back on this one",
        "confidence is not the same thing as being right",
        "this is a headline pretending to be an argument",
        "the actual history here is more interesting than the flattened version",
        "somebody skipped several steps to get to this conclusion",
        "this take survives exactly until you check one primary source",
        "the nuance got left on the cutting room floor here",
        "this is hype wearing an analysis costume",
        "the claim is doing more marketing than the product",
        "history is not this tidy, and neither is this argument",
        "this is confident in inverse proportion to how well-supported it is",
        "the specifics are the whole point, and they're missing here",
        "this deserves a footnote, not a headline",
        "the interesting part of this story got cut for pacing",
        "someone mistook 'simple' for 'true' here",
        "this argument needed one more round of scrutiny before it left the house",
    ],
    Register.GIDDY: [
        "this just happened and I need a minute",
        "dropping everything for this",
        "okay this is actually huge",
        "did NOT expect to be this excited before coffee",
        "reading this three times just to make sure it's real",
        "everyone needs to see this right now",
        "this is the kind of news that ruins your afternoon plans in the best way",
        "genuinely yelled a little",
        "this changes the conversation starting immediately",
        "can't believe this is real and also can't stop smiling",
        "the timeline is going to be insufferable about this, and it's deserved",
        "putting everything else down for this",
        "this is the good kind of can't-sit-still",
        "not being dramatic, this is actually a big deal",
        "just found this out and had to tell someone immediately",
        "this is the best kind of interruption",
        "the excitement is not going to be contained to one post",
        "still buzzing about this",
    ],
}


def get_flavor_fragment(register: Register) -> str:
    """Sample one flavor fragment for the given register."""
    return random.choice(VOICE_BANK[register])
